"""initial schema: shipments, documents, validation_results

Revision ID: 0121b40f9ac3
Revises: 
Create Date: 2026-10-05 15:30:26.887343
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "0121b40f9ac3"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'EXTRACTING', 'EXTRACTED', 'FAILED', name='shipment_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipments_status'), 'shipments', ['status'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('shipment_id', sa.Uuid(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('file_type', sa.String(length=32), nullable=False),
    sa.Column('detected_doc_type', sa.Enum('COMMERCIAL_INVOICE', 'PACKING_LIST', 'BILL_OF_LADING', 'UNKNOWN', name='document_type'), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('extracted_data', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('status', sa.Enum('UPLOADED', 'EXTRACTING', 'COMPLETED', 'FAILED', name='document_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_detected_doc_type'), 'documents', ['detected_doc_type'], unique=False)
    op.create_index(op.f('ix_documents_shipment_id'), 'documents', ['shipment_id'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_table('validation_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('shipment_id', sa.Uuid(), nullable=False),
    sa.Column('rule_id', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.Enum('HIGH', 'MEDIUM', 'LOW', 'INFO', name='severity'), nullable=False),
    sa.Column('field_name', sa.String(length=128), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('source_doc_type', sa.String(length=64), nullable=True),
    sa.Column('target_doc_type', sa.String(length=64), nullable=True),
    sa.Column('source_value', sa.Text(), nullable=True),
    sa.Column('target_value', sa.Text(), nullable=True),
    sa.Column('evidence_snippet', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_results_rule_id'), 'validation_results', ['rule_id'], unique=False)
    op.create_index(op.f('ix_validation_results_severity'), 'validation_results', ['severity'], unique=False)
    op.create_index(op.f('ix_validation_results_shipment_id'), 'validation_results', ['shipment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validation_results_shipment_id'), table_name='validation_results')
    op.drop_index(op.f('ix_validation_results_severity'), table_name='validation_results')
    op.drop_index(op.f('ix_validation_results_rule_id'), table_name='validation_results')
    op.drop_table('validation_results')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_shipment_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_detected_doc_type'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_shipments_status'), table_name='shipments')
    op.drop_table('shipments')
    # ### end Alembic commands ###
